version: "3.5"

services:
  obp_institution_db:
    image: openbookpublishers/obp_institution_db
    container_name: "obp_institution_db"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./config/db.env

  obp_institution_api:
    build: ./
    container_name: "obp_institution_api"
    restart: unless-stopped
    ports:
      - 8181:8080
    environment:
      - INSTITUTIONDB_HOST=obp_institution_db
      - API_DEBUG=True
      - ALLOW_ORIGIN=http://172.21.0.5
    env_file:
      - ./config/db.env
    depends_on:
      - obp_institution_db

-volumes:
  db:
